---
- name: Check postgresql started
  become: yes
  systemd:
    name: postgresql
    state: started
    daemon_reload: true

- name: Install required system packages
  become: yes
  apt:
    pkg:
      - python3-psycopg2
    state: latest
    update_cache: true

- name: Create user
  become: yes
  postgresql_user:
    name: "{{ user_name }}"
    password: "{{ user_password }}"

- name: Grant user access to databases
  become: yes
  postgresql_user:
    db: "{{ item }}"
    name: "{{ user_name }}"
  loop: "{{ databases }}"

- name: Grant user previleges to databases
  become: yes
  postgresql_privs:
    db: "{{ item }}"
    roles: "{{ user_name }}"
    type: database
    privs: "{{ privileges }}"
  loop: "{{ databases }}"