---
- name: Creates telegraf opt directory
  become: yes
  file:
    path: /opt/telegraf/
    state: directory
    owner: root

- name: Update apt and install telegraf
  become: yes
  apt:
    name: telegraf
    state: latest
    update_cache: true

- name: Copy telegraf service systemd file
  become: yes
  copy:
    src: telegraf.service
    dest: /lib/systemd/system/
    owner: root
    group: root
    mode: 0644

- name: Copy telegraf service configuration file
  become: yes
  copy:
    src: telegraf.conf
    dest: /etc/telegraf/
    owner: root
    group: root
    mode: 0644

- name: Copy telegraf outputs configuration file
  become: yes
  copy:
    src: outputs_prometheus.conf
    dest: /etc/telegraf/telegraf.d/
    owner: root
    group: root
    mode: 0644