---
- name: Create lvm for postgresql data
  become: yes
  hosts: services-servers
  roles:
    - ./roles/lvm
  vars:
    vg: data
    pvs: /dev/vdb
    lv: postgresql_data
    lv_size: 500M
    device_path: /dev/data/postgresql_data
    directory: /var/lib/postgresql/14/main

- name: Create lvm for postgresql logs
  become: yes
  hosts: services-servers
  roles:
    - ./roles/lvm
  vars:
    vg: data
    pvs: /dev/vdb
    lv: postgresql_logs
    lv_size: 20M
    device_path: /dev/data/postgresql_logs
    directory: /var/log/postgresql

- name: Install Postgresql
  become: yes
  hosts: services-servers
  roles:
    - ./roles/postgresql-server
  vars:
    data_directory: /var/lib/postgresql/14/main
    logs_directory: /var/log/postgresql

- name: Create Postgresql databases
  become: yes
  hosts: services-servers
  roles:
    - ./roles/postgresql-database
  vars:
    databases:
      - freedom

- name: Create service user with access to Postgresql databases
  become: yes
  hosts: services-servers
  roles:
    - ./roles/postgresql-user
  vars:
    user_name: "{{ lookup('env', 'POSTGRES_USER') }}"
    user_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
    privileges: ALL
    databases:
      - freedom