global:
  scrape_interval: 13s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - follow_redirects: true
      scheme: http
      timeout: 10s
      api_version: v2
      static_configs:
        - targets: [ ]
scrape_configs:

  # Databases

  - job_name: "database_nodes_metrics"
    static_configs:
      - targets: [ "localhost:9273" ]
        labels:
          type: database
          instance: database server 1

  # Services

  - job_name: "service_nodes_metrics"
    static_configs:
      - targets: [ "localhost:9273" ]
        labels:
          type: service
          instance: services server 1