---
- name: Update apt and install postgresql
  become: yes
  apt:
    name: postgresql-14
    state: latest
    update_cache: true

- name: Check postgresql started
  become: yes
  systemd:
    name: postgresql
    state: started
    daemon_reload: true