name: Install Database Postgresql
on: workflow_dispatch
jobs:
  install_database_postgresql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Add SSH key to agent
        run: echo ${{ secrets.ANSIBLE_PRIVATE_KEY }}

      - name: Add SSH key to agent
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<<"${{ secrets.ANSIBLE_PRIVATE_KEY }}"

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i inventory/inventory -f 1 playbooks/database/server-1.yaml --ssh-common-args='-o StrictHostKeyChecking=no'
        env:
          ANSIBLE_PRIVATE_KEY: ${{ secrets.ANSIBLE_PRIVATE_KEY }}

