name: Install Docker
on: workflow_dispatch
jobs:
  install-docker:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Ansible and Key
        run: |
          bash ./.github/scripts/setup-ansible-and-key.sh

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i inventory/inventory -f 1 playbooks/docker/docker.yaml --ssh-common-args='-o StrictHostKeyChecking=no' -u root