name: Setup Ansible and Key

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Setup Key
        run: |
          mkdir "$HOME/.ssh"
          echo "${{ secrets.SSH_KEY }}" > "$HOME/.ssh/id_rsa"
          chmod 700 "$HOME/.ssh/"
          chmod 600 "$HOME/.ssh/id_rsa"
